/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Schedule as PrismaSchedule,
  EventType as PrismaEventType,
  Availability as PrismaAvailability,
  User as PrismaUser,
} from "@prisma/client";

export class ScheduleServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ScheduleCountArgs, "select">): Promise<number> {
    return this.prisma.schedule.count(args);
  }

  async schedules<T extends Prisma.ScheduleFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleFindManyArgs>
  ): Promise<PrismaSchedule[]> {
    return this.prisma.schedule.findMany<Prisma.ScheduleFindManyArgs>(args);
  }
  async schedule<T extends Prisma.ScheduleFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleFindUniqueArgs>
  ): Promise<PrismaSchedule | null> {
    return this.prisma.schedule.findUnique(args);
  }
  async createSchedule<T extends Prisma.ScheduleCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleCreateArgs>
  ): Promise<PrismaSchedule> {
    return this.prisma.schedule.create<T>(args);
  }
  async updateSchedule<T extends Prisma.ScheduleUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleUpdateArgs>
  ): Promise<PrismaSchedule> {
    return this.prisma.schedule.update<T>(args);
  }
  async deleteSchedule<T extends Prisma.ScheduleDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ScheduleDeleteArgs>
  ): Promise<PrismaSchedule> {
    return this.prisma.schedule.delete(args);
  }

  async findEventType(
    parentId: number,
    args: Prisma.EventTypeFindManyArgs
  ): Promise<PrismaEventType[]> {
    return this.prisma.schedule
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .eventType(args);
  }

  async findAvailability(
    parentId: number,
    args: Prisma.AvailabilityFindManyArgs
  ): Promise<PrismaAvailability[]> {
    return this.prisma.schedule
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .availability(args);
  }

  async getUser(parentId: number): Promise<PrismaUser | null> {
    return this.prisma.schedule
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
