/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DailyEventReference as PrismaDailyEventReference,
  Booking as PrismaBooking,
} from "@prisma/client";

export class DailyEventReferenceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DailyEventReferenceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.dailyEventReference.count(args);
  }

  async dailyEventReferences<T extends Prisma.DailyEventReferenceFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.DailyEventReferenceFindManyArgs>
  ): Promise<PrismaDailyEventReference[]> {
    return this.prisma.dailyEventReference.findMany<Prisma.DailyEventReferenceFindManyArgs>(
      args
    );
  }
  async dailyEventReference<T extends Prisma.DailyEventReferenceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DailyEventReferenceFindUniqueArgs>
  ): Promise<PrismaDailyEventReference | null> {
    return this.prisma.dailyEventReference.findUnique(args);
  }
  async createDailyEventReference<
    T extends Prisma.DailyEventReferenceCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.DailyEventReferenceCreateArgs>
  ): Promise<PrismaDailyEventReference> {
    return this.prisma.dailyEventReference.create<T>(args);
  }
  async updateDailyEventReference<
    T extends Prisma.DailyEventReferenceUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.DailyEventReferenceUpdateArgs>
  ): Promise<PrismaDailyEventReference> {
    return this.prisma.dailyEventReference.update<T>(args);
  }
  async deleteDailyEventReference<
    T extends Prisma.DailyEventReferenceDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.DailyEventReferenceDeleteArgs>
  ): Promise<PrismaDailyEventReference> {
    return this.prisma.dailyEventReference.delete(args);
  }

  async getBooking(parentId: number): Promise<PrismaBooking | null> {
    return this.prisma.dailyEventReference
      .findUnique({
        where: { id: parentId },
      })
      .booking();
  }
}
