/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, ReminderMail as PrismaReminderMail } from "@prisma/client";

export class ReminderMailServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ReminderMailCountArgs, "select">
  ): Promise<number> {
    return this.prisma.reminderMail.count(args);
  }

  async reminderMails<T extends Prisma.ReminderMailFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReminderMailFindManyArgs>
  ): Promise<PrismaReminderMail[]> {
    return this.prisma.reminderMail.findMany<Prisma.ReminderMailFindManyArgs>(
      args
    );
  }
  async reminderMail<T extends Prisma.ReminderMailFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReminderMailFindUniqueArgs>
  ): Promise<PrismaReminderMail | null> {
    return this.prisma.reminderMail.findUnique(args);
  }
  async createReminderMail<T extends Prisma.ReminderMailCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReminderMailCreateArgs>
  ): Promise<PrismaReminderMail> {
    return this.prisma.reminderMail.create<T>(args);
  }
  async updateReminderMail<T extends Prisma.ReminderMailUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReminderMailUpdateArgs>
  ): Promise<PrismaReminderMail> {
    return this.prisma.reminderMail.update<T>(args);
  }
  async deleteReminderMail<T extends Prisma.ReminderMailDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ReminderMailDeleteArgs>
  ): Promise<PrismaReminderMail> {
    return this.prisma.reminderMail.delete(args);
  }
}
